version: '3.1'

services:
  order-ms:
    image: docker.io/rcolvara/order-ms-shop-now:1.0
    hostname: order-ms
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://172.17.0.1:5432/postgres"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512MB"
  user-ms:
    image: docker.io/rcolvara/user-ms-shop-now:1.0
    hostname: user-ms
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://172.17.0.1:5432/postgres?user=postgres&password=postgres"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512MB"
  product-ms:
    image: docker.io/rcolvara/product-ms-shop-now:1.0
    hostname: product-ms
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://172.17.0.1:5432/postgres?user=postgres&password=postgres"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512MB"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "512MB"


