version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop-now
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: now
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:
